global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ups-primary'
    scrape_interval: 60s
    metrics_path: /ups_metrics
    static_configs:
      - targets: ['nut-exporter:9199']
        labels:
          ups:  "primary"
    params:
      ups: [ "ups" ]
      username: [ "monuser" ]
      password: [ "secret" ]
      server: [ "ups.internal.ltek.me" ]

  - job_name: openwrt
    scrape_interval: 5s
    static_configs:
      - targets: ['gw.internal.ltek.me:9100']

  - job_name: pve
    scrape_interval: 15s
    metrics_path: /pve
    static_configs:
      - targets: ['monit.internal.ltek.me:9221']
    params:
      cluster: ['1']
      node: ['0']
      target: ['pve0.internal.ltek.me']

  - job_name: kuma
    scrape_interval: 20s
    static_configs:
      - targets: ['monit.internal.ltek.me:3001']
    basic_auth:
      password_file: /kuma.password