global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ups-primary'
    scrape_interval: 60s
    metrics_path: /ups_metrics
    static_configs:
      - targets: ['nut-exporter:9199']
        labels:
          ups:  "primary"
    params:
      ups: [ "ups" ]
      username: [ "monuser" ]
      password: [ "secret" ]
      server: [ "ups.internal.ltek.me" ]

  - job_name: openwrt
    scrape_interval: 5s
    static_configs:
      - targets: ['gw.internal.ltek.me:9100']

