ruleset(name="alloy"){
  action(type="omfwd" Target="alloy" Port="601" Protocol="tcp" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted")
}
module(load="imudp")
module(load="imtcp")
input(type="imudp" port="514" ruleset="alloy")
input(type="imtcp" port="514" ruleset="alloy")
