{
 "title": "Linux ISO",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Transfer status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app) (qbittorrent_up_info_data_total{job=\"linux-iso\"})",
     "legendFormat": "In session upload"
    },
    {
     "expr": "sum by (app) (qbittorrent_alltime_ul_total{job=\"linux-iso\"})",
     "legendFormat": "All time upload"
    },
    {
     "expr": "sum by (app) (qbittorrent_dl_info_data_total{job=\"linux-iso\"})",
     "legendFormat": "In session download"
    },
    {
     "expr": "qbittorrent_alltime_dl_total{job=\"linux-iso\"}",
     "legendFormat": "All time download"
    }
   ]
  },
  {
   "title": "Accumulated ratio in session",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum by (app) (qbittorrent_alltime_ul_total{job=\"linux-iso\"})) / (sum by (app) (qbittorrent_alltime_dl_total{job=\"linux-iso\"}))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(qbittorrent_dl_info_data_total{job=\"linux-iso\"}[20s])"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(qbittorrent_up_info_data_total{job=\"linux-iso\"}[20s])"
    }
   ]
  },
  {
   "title": "Transfer Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "-(rate(qbittorrent_dl_info_data_total{job=\"linux-iso\"}[20s]))",
     "legendFormat": "Download"
    },
    {
     "expr": "rate(qbittorrent_up_info_data_total{job=\"linux-iso\"}[20s])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Torrents by status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "qbittorrent_torrents_count{job=\"linux-iso\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}