{
 "title": "OpenWRT",
 "description": "Dashboard for OpenWRT routers with installed lua scripts.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"openwrt\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',job=\"openwrt\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',job=\"openwrt\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"openwrt\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',job=\"openwrt\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=\"openwrt\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"openwrt\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{job=\"openwrt\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{job=\"openwrt\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"openwrt\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"openwrt\"} - node_memory_MemFree_bytes{job=\"openwrt\"} - (node_memory_Cached_bytes{job=\"openwrt\"} + node_memory_Buffers_bytes{job=\"openwrt\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"openwrt\"} + node_memory_Buffers_bytes{job=\"openwrt\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"openwrt\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"openwrt\"} - node_memory_SwapFree_bytes{job=\"openwrt\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Network Traffic by Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"openwrt\"}[5m])/1024",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"openwrt\"}[5m])/1024",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    },
    {
     "expr": "irate(node_network_receive_packets_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    }
   ]
  },
  {
   "title": "Transmit Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{job=\"openwrt\"}/1024/1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{job=\"openwrt\"}/1024/1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Packets Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_transmit_packets_total{job=\"openwrt\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Packets Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_receive_packets_total{job=\"openwrt\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Top NAT Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "topk(15, node_nat_traffic{job=\"openwrt\"}/1024/1024)",
     "legendFormat": "Dest= {{dest}} # Source= {{src}}"
    }
   ]
  },
  { "title": "Network Traffic Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Network Traffic Drop",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  {
   "title": "Network Traffic Multicast",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Receive multicast"
    }
   ]
  },
  {
   "title": "Network Traffic Compressed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_compressed_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Receive compressed"
    },
    {
     "expr": "irate(node_network_transmit_compressed_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Transmit compressed"
    }
   ]
  },
  {
   "title": "Network Traffic Frame",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_frame_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Receive frame"
    }
   ]
  },
  {
   "title": "Network Traffic Fifo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_fifo_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Receive fifo"
    },
    {
     "expr": "irate(node_network_transmit_fifo_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Transmit fifo"
    }
   ]
  },
  {
   "title": "Network Traffic Colls",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_colls_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Transmit colls"
    }
   ]
  },
  {
   "title": "Network Traffic Carrier",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_carrier_total{job=\"openwrt\"}[5m])",
     "legendFormat": "{{device}} - Statistic transmit_carrier"
    }
   ]
  },
  {
   "title": "NF Contrack",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{job=\"openwrt\"}",
     "legendFormat": "NF conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{job=\"openwrt\"}",
     "legendFormat": "NF conntrack limit"
    }
   ]
  }
 ]
}