{
 "title": "Proxmox",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Resources",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (id, name) (pve_guest_info{job=\"pve\"})"
    },
    {
     "expr": "sum by (id) (pve_up{job=~\"pve\"} and on (id, job) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{job=~\"pve\"} and on (id, job) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{job=~\"pve\"} and on (id, job) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{job=~\"pve\",template!=\"1\"} / pve_memory_size_bytes and on (id, job) pve_guest_info and on (id) pve_up==1)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{job=~\"pve\"} and on (id, job) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_usage_bytes{job=~\"pve\"} / pve_disk_size_bytes and on (id, job) pve_guest_info{type=\"lxc\"})"
    }
   ]
  },
  {
   "title": "CPU history",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{job=~\"pve\"} and on(id) pve_node_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory history",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{job=~\"pve\"} and on(id) pve_node_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Guests CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "((pve_cpu_usage_ratio{job=~\"pve\"} / pve_cpu_usage_limit) * on(id, job) group_left(name, type) pve_guest_info) and on(id, job) pve_up == 1",
     "legendFormat": "{{id}} ({{name}})"
    }
   ]
  },
  {
   "title": "Guests memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{job=~\"pve\"} / pve_memory_size_bytes * on(id, job) group_left(name, type) pve_guest_info) and on(id, job) pve_up == 1",
     "legendFormat": "{{id}} ({{name}})"
    }
   ]
  },
  {
   "title": "Network IO/s Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_network_transmit_bytes_total{job=~\"pve\"}[5m])* on(id, job) group_left(name, type) pve_guest_info) and on(id, job) pve_up == 1",
     "legendFormat": "{{id}} ({{name}})"
    }
   ]
  },
  {
   "title": "Network IO/s Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_network_receive_bytes_total{job=~\"pve\"}[5m])* on(id, job) group_left(name, type) pve_guest_info) and on(id, job) pve_up == 1",
     "legendFormat": "{{id}} ({{name}})"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_disk_written_bytes_total{job=~\"pve\"}[5m]) * on(id, job) group_left(name, type) pve_guest_info) and on(id, job) pve_up == 1",
     "legendFormat": "{{id}} ({{name}})"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_disk_read_bytes_total{job=~\"pve\"}[5m]) * on(id, job) group_left(name, type) pve_guest_info) and on(id, job) pve_up == 1",
     "legendFormat": "{{id}} ({{name}})"
    }
   ]
  }
 ]
}