{
 "title": "UPS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UPS Load",
   "type": "timeseries",
   "description": "UPS Load",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{ups=\"primary\"}",
     "legendFormat": "Load %"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{ups=\"primary\"}",
     "legendFormat": "Volt"
    }
   ]
  },
  {
   "title": "Line Input Voltage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{job=\"ups-primary\"}",
     "legendFormat": "Volt"
    }
   ]
  }
 ]
}